#+TITLE: Physics Practical

Data obtained during a physics experiment often needs to be processed. Calculating the averages and uncertainties of each value in a large data-set can be tedious. The use of computers and software can make this process easier.

The examples given here are organised in sub directories, which share the contents of the =functions= package (I couldn't think of a better name!).

* Important Files

For each experiment this is how the files are used:

- =./data/control_variables.py= contains the experimental control variables
- =./data/measured_variables.csv= is the raw data loaded by the program
- =./data/processed_data.csv= is the file where the program writes the processed data
- =./experiment.py= is the main script, responsible for the data processing

* Running the Project

The program will process the data and write it to a csv file. Assuming all the dependencies are satisfied, a graph is also presented (not saved automatically).

/NB. instructions given for linux/unix systems/

In a virtual-environment (or globally) install the dependencies with this command:

#+begin_src shell

python3 -m pip install -r requirements.txt

#+end_src

Switch to an experiment:

#+begin_src shell

cd ./pressure

#+end_src

Entry point for the project is =experiment.py=, so run like this:

#+begin_src shell

python3 experiment.py

#+end_src

Alternatively make the script executable and run:

#+begin_src shell

chmod u+x experiment.py
./experiment.py

#+end_src

